[package]
name = "link-extractor"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
reqwest = { version = "0.12", features = ["json"] }
select = "0.6.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
