[package]
name = "async-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
reqwest = { version = "0.12.24", features = ["blocking", "json"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
